import './style.css';
import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createDuck,createWeapon} from './models.js';
import {createLevel,createSky,loadMaterials} from './world.js';
import {GUNS,DIFFICULTY,BOUNDS,blocked,moveActor,lineBlocked,reloadAmmo,formatTime,waveSize,routeTo} from './rules.js';
const $=id=>document.getElementById(id),canvas=$('scene'),touch=matchMedia('(pointer:coarse)').matches,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
if(touch)document.body.classList.add('touch-device');
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});}catch(e){$('fatal').hidden=false;throw e;}
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.055,180);camera.rotation.order='YXZ';scene.add(camera);
const hemi=new THREE.HemisphereLight(0xb9c2c3,0x373c35,1.4);scene.add(hemi);const sun=new THREE.DirectionalLight(0xe7dec5,2.7);sun.position.set(-17,32,-30);sun.castShadow=true;Object.assign(sun.shadow.camera,{left:-42,right:42,top:42,bottom:-42,near:1,far:100});sun.shadow.bias=-.0003;sun.shadow.normalBias=.035;sun.shadow.mapSize.set(2048,2048);scene.add(sun);scene.add(sun.target);
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const envTarget=pmrem.fromScene(room,.04);scene.environment=envTarget.texture;scene.environmentIntensity=.3;room.dispose();pmrem.dispose();
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new OutputPass());const grade=new ShaderPass({uniforms:{tDiffuse:{value:null},time:{value:0},grain:{value:reduced?0:.013}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform sampler2D tDiffuse;uniform float time;uniform float grain;varying vec2 vUv;void main(){vec3 c=texture2D(tDiffuse,vUv).rgb;float l=dot(c,vec3(.2126,.7152,.0722));c=mix(vec3(l),c,.78);vec2 p=vUv-.5;float vig=1.-smoothstep(.20,.75,length(p))*.26;c*=vig;float n=fract(sin(dot(vUv*917.,vec2(12.9898,78.233))+time)*43758.5453)-.5;c+=n*grain;gl_FragColor=vec4(c,1.);}`});composer.addPass(grade);
let low=touch,level,sky,map='foundry',state='loading',time=0,elapsed=0,wave=0,kills=0,score=0,health=100,timeLeft=300,transition=0,noticeTimer=0,feedTimer=0,hitTimer=0,damage=0,shots=0,hits=0;
let yaw=0,pitch=0,ads=0,aim=false,crouch=false,sprinting=false,fireHeld=false,semiReady=true,gunIndex=0,reloadRemaining=0,reloadTotal=1,shotCooldown=0,recoil=0,lookSwayX=0,lookSwayY=0,footstepTimer=0,flashTimer=0;
const player=new THREE.Vector3(),keys=new Set(),joystick={x:0,z:0},ammoState=GUNS.map(g=>({ammo:g.capacity,reserve:g.reserve})),actors=[],effects=[],ray=new THREE.Raycaster();
const guns=GUNS.map((_,i)=>createWeapon(i)),weaponRig=new THREE.Group();camera.add(weaponRig);for(const g of guns){weaponRig.add(g);g.visible=false;g.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.depthTest=false;o.material.depthWrite=false;o.renderOrder=20;o.castShadow=false;o.receiveShadow=false;}});}
weaponRig.visible=false;const hero=createDuck({low:touch});scene.add(hero);
const muzzleLight=new THREE.PointLight(0xffc584,0,5,2);camera.add(muzzleLight);muzzleLight.position.set(.1,-.1,-1.2);
// Sound is synthesized locally: no external audio requests or playback before interaction.
let audio,master,windGain,muted=false;function initAudio(){if(audio){audio.resume();return;}try{audio=new(window.AudioContext||window.webkitAudioContext)();master=audio.createGain();master.gain.value=muted?0:.65;master.connect(audio.destination);const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()-.5)*.35;const wind=audio.createBufferSource();wind.buffer=buffer;wind.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=280;windGain=audio.createGain();windGain.gain.value=.07;wind.connect(filter).connect(windGain).connect(master);wind.start();}catch{}}
function sound(type){if(!audio||muted)return;const now=audio.currentTime;if(type==='shot'){const length=.15,b=audio.createBuffer(1,Math.floor(audio.sampleRate*length),audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);const s=audio.createBufferSource();s.buffer=b;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=gunIndex?3100:2100;const g=audio.createGain();g.gain.value=.48;s.connect(filter).connect(g).connect(master);s.start();tone(gunIndex?130:85,.12,.20,'triangle');}else if(type==='hit')tone(1150,.035,.10,'sine');else if(type==='reload')tone(340,.05,.08,'square');else if(type==='step')tone(65,.035,.07,'triangle');else if(type==='hurt')tone(80,.13,.1,'sine');else if(type==='ready')tone(700,.10,.06,'sine');}
function tone(freq,duration,volume,type){const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,now);o.frequency.exponentialRampToValueAtTime(freq*.4,now+duration);g.gain.setValueAtTime(volume,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g).connect(master);o.start();o.stop(now+duration);}
function notify(message,duration=2){$('notice').textContent=message;noticeTimer=duration;}
function disposeActor(model){scene.remove(model);model.traverse(o=>{if(o.geometry?.userData.owned)o.geometry.dispose();});}
function setMap(value){map=value;actors.splice(0).forEach(a=>disposeActor(a.model));effects.splice(0).forEach(e=>{scene.remove(e.obj);e.obj.geometry?.dispose();e.obj.material?.dispose();});if(level){scene.remove(level.root);level.dispose();}if(sky){scene.remove(sky);sky.geometry.dispose();sky.material.dispose();}low=$('quality').value==='low'||($('quality').value==='auto'&&touch);level=createLevel(map,low);scene.add(level.root);sky=createSky(scene,map);const night=map==='temple';scene.fog=new THREE.FogExp2(night?0x192a32:0x737976,night?.029:.021);hemi.color.set(night?0x8ba7b6:0xc4cac5);hemi.intensity=night?1.3:1.6;sun.color.set(night?0x91afbd:0xede1c7);sun.intensity=night?1.6:2.7;scene.environmentIntensity=night?.17:.3;renderer.toneMappingExposure=night?1.15:1.04;applyQuality();$('brief').textContent=night?'沿石燈籠穿越神社庭院，在雨幕中辨識敵人。完成三波清剿，確保通道安全。':'穿越廢棄工業街區，在掩體間壓制敵方守衛。完成三波清剿，確保街區安全。';$('mapWeather').textContent=night?'雨夜 / 近距離交戰':'陰天 / 工業廢墟';$('zoneLabel').textContent=night?'SHADOW SHRINE':'IRON DISTRICT';document.querySelectorAll('[data-map]').forEach(b=>{b.classList.toggle('selected',b.dataset.map===map);b.setAttribute('aria-pressed',String(b.dataset.map===map));});}
function applyQuality(){renderer.setPixelRatio(Math.min(devicePixelRatio,low?1.25:1.8));renderer.setSize(innerWidth,innerHeight);composer.setPixelRatio(renderer.getPixelRatio());composer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=!low;grade.uniforms.grain.value=reduced||low?0:.011;}
function hud(){const a=ammoState[gunIndex];$('health').textContent=Math.max(0,Math.ceil(health));$('healthFill').style.width=Math.max(0,health)+'%';$('healthFill').style.background=health<30?'#bb6651':'#c8d0b4';$('ammo').textContent=String(a.ammo).padStart(2,'0');$('reserve').textContent='/ '+a.reserve;$('weaponName').textContent=GUNS[gunIndex].name;$('reloadLabel').textContent=reloadRemaining?'換彈中':gunIndex?'SEMI / 9 MM':'AUTO / 5.56';$('wave').textContent=String(wave).padStart(2,'0')+' / 03';$('killScore').textContent=String(kills).padStart(2,'0');$('score').textContent=String(score).padStart(4,'0');$('posture').textContent=crouch?'蹲姿':sprinting?'疾跑':'站立';}
function resetInput(){keys.clear();joystick.x=joystick.z=0;fireHeld=false;semiReady=true;aim=false;sprinting=false;lookId=null;stickId=null;$('stick').firstElementChild.style.transform='';$('touchAim').setAttribute('aria-pressed','false');$('touchSprint').setAttribute('aria-pressed','false');}
function pointerLock(){if(touch)return;try{const p=canvas.requestPointerLock?.();p?.catch(()=>notify('按住滑鼠拖曳轉向；點擊畫面可再次鎖定游標',4));}catch{notify('按住滑鼠拖曳轉向',3);}}
function start(){if(!level)return;initAudio();resetInput();actors.splice(0).forEach(a=>disposeActor(a.model));player.set(level.spawn.x,0,level.spawn.z);yaw=0;pitch=0;health=100;wave=kills=score=shots=hits=0;elapsed=0;timeLeft=DIFFICULTY[$('difficulty').value].time;reloadRemaining=shotCooldown=recoil=ads=transition=0;gunIndex=Number($('primaryWeapon').value);ammoState.forEach((a,i)=>{a.ammo=GUNS[i].capacity;a.reserve=GUNS[i].reserve;});crouch=false;$('touchCrouch').setAttribute('aria-pressed','false');hero.visible=false;weaponRig.visible=true;guns.forEach((g,i)=>g.visible=i===gunIndex);state='playing';$('lobby').hidden=true;$('hud').hidden=false;$('touch').hidden=!touch;$('overlay').hidden=true;document.body.classList.add('playing');if(windGain)windGain.gain.value=.07;spawnWave();pointerLock();if(touch)fullscreen();}
function spawnWave(){wave++;transition=0;const count=waveSize(wave,$('difficulty').value);for(let i=0;i<count;i++){const candidates=level.spawnPoints.filter(p=>Math.hypot(p.x-player.x,p.z-player.z)>13&&!blocked(p.x,p.z,level.boxes,.5));let pos=candidates[i%candidates.length]||level.spawnPoints[0];let x=pos.x,z=pos.z;for(let attempt=0;attempt<20;attempt++){if(!actors.some(a=>Math.hypot(a.model.position.x-x,a.model.position.z-z)<1.2)&&!blocked(x,z,level.boxes,.5))break;x=pos.x+(Math.random()-.5)*3;z=pos.z+(Math.random()-.5)*3;}const model=createDuck({enemy:true,low:true});model.position.set(x,0,z);scene.add(model);const actor={model,hp:DIFFICULTY[$('difficulty').value].hp,cool:1+Math.random(),path:[],repath:Math.random(),strafe:Math.random()>.5?1:-1,phase:Math.random()*6};model.traverse(o=>{if(o.isMesh)o.userData.actor=actor;});actors.push(actor);}if(wave>1){health=Math.min(100,health+20);ammoState.forEach((a,i)=>a.reserve+=GUNS[i].capacity);hud();}notify(`第 ${wave} 波 / 清剿 ${count} 名守衛`,3);hud();}
function reload(){const a=ammoState[gunIndex];if(state!=='playing'||reloadRemaining||a.ammo===GUNS[gunIndex].capacity)return;if(!a.reserve){notify('此武器備用彈藥耗盡，切換另一把武器');return;}reloadTotal=GUNS[gunIndex].reload;reloadRemaining=reloadTotal;aim=false;sound('reload');hud();}
function switchGun(index){if(state!=='playing'||index===gunIndex)return;gunIndex=index;reloadRemaining=0;shotCooldown=.3;recoil=.08;guns.forEach((g,i)=>g.visible=i===index);sound('reload');hud();}
function tracer(from,to,color,lifetime=.065){const geom=new THREE.BufferGeometry().setFromPoints([from,to]),obj=new THREE.Line(geom,new THREE.LineBasicMaterial({color,transparent:true,opacity:.8,depthWrite:false}));scene.add(obj);effects.push({obj,life:lifetime,total:lifetime});}
function impact(point,hit){const count=low?4:8,arr=new Float32Array(count*3),vel=[];for(let i=0;i<count;i++){arr.set(point.toArray(),i*3);vel.push(new THREE.Vector3((Math.random()-.5)*3,Math.random()*2,(Math.random()-.5)*3));}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(arr,3));const obj=new THREE.Points(geo,new THREE.PointsMaterial({color:hit?0xe8d6aa:0xbdb9a5,size:.04,transparent:true,opacity:.8,depthWrite:false}));scene.add(obj);effects.push({obj,life:.28,total:.28,vel});}
function shoot(){if(state!=='playing'||reloadRemaining||shotCooldown>0)return;const weapon=GUNS[gunIndex],a=ammoState[gunIndex];if(!weapon.automatic&&!semiReady)return;if(a.ammo<=0){reload();semiReady=false;return;}a.ammo--;shots++;semiReady=false;shotCooldown=weapon.delay;recoil=Math.min(.10,recoil+weapon.recoil);flashTimer=.045;sound('shot');camera.updateMatrixWorld(true);ray.setFromCamera(new THREE.Vector2((Math.random()-.5)*(1-ads)*.012,(Math.random()-.5)*(1-ads)*.012),camera);ray.far=100;const meshes=[...level.rayTargets];for(const actor of actors)actor.model.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh)meshes.push(o);});scene.updateMatrixWorld(true);const hit=ray.intersectObjects(meshes,false)[0];const end=hit?.point||ray.ray.at(80,new THREE.Vector3());const gun=guns[gunIndex];const origin=gun.userData.muzzle.getWorldPosition(new THREE.Vector3());tracer(origin,end,0xffd8a0);if(hit){const actor=hit.object.userData.actor;impact(hit.point,!!actor);if(actor){hits++;const head=hit.point.y-actor.model.position.y>1.4;actor.hp-=weapon.damage*(head?1.8:1);hitTimer=.13;$('hitmarker').style.color=head?'#d6b579':'#eee6cb';sound('hit');if(actor.hp<=0){kills++;score+=head?150:100;$('killfeed').textContent=`DUCK 007　›　守衛 ${head?'／精準命中':''}`;feedTimer=3.5;disposeActor(actor.model);actors.splice(actors.indexOf(actor),1);if(!actors.length)transition=3;}}}hud();}
function pause(){if(state!=='playing')return;state='paused';resetInput();document.exitPointerLock?.();$('touch').hidden=true;$('overlayTag').textContent='TACTICAL PAUSE';$('overlayTitle').textContent='行動暫停';$('overlayCopy').textContent='準備好後，繼續你的任務。';$('stats').innerHTML='';$('continue').textContent='繼續行動 →';$('overlay').hidden=false;if(windGain)windGain.gain.value=0;}
function resume(){state='playing';$('overlay').hidden=true;$('touch').hidden=!touch;if(windGain)windGain.gain.value=.07;pointerLock();}
function finish(win){state=win?'won':'lost';resetInput();document.exitPointerLock?.();$('touch').hidden=true;$('overlayTag').textContent=win?'OPERATION COMPLETE':'OPERATION FAILED';$('overlayTitle').textContent=win?'街區安全，任務完成。':'行動失敗';$('overlayCopy').textContent=win?'全數目標已清除。特工，返回總部。':health<=0?'你已失去戰鬥能力。利用掩體、蹲姿與瞄準，重新規劃路線。':'行動時間已結束。整裝後再次出發。';$('stats').replaceChildren();for(const [label,value]of [['行動分數',score],['清除目標',kills],['命中率',(shots?Math.round(hits/shots*100):0)+'%'],['經過時間',formatTime(elapsed)]]){const d=document.createElement('div'),s=document.createElement('span'),b=document.createElement('b');s.textContent=label;b.textContent=value;d.append(s,b);$('stats').append(d);}$('continue').textContent='重新行動 →';$('overlay').hidden=false;if(windGain)windGain.gain.value=0;}
function returnLobby(){state='lobby';resetInput();document.exitPointerLock?.();$('overlay').hidden=true;$('hud').hidden=true;$('touch').hidden=true;$('lobby').hidden=false;document.body.classList.remove('playing');weaponRig.visible=false;hero.visible=true;actors.splice(0).forEach(a=>disposeActor(a.model));if(windGain)windGain.gain.value=0;}
function tickActors(dt){const diff=DIFFICULTY[$('difficulty').value];for(const a of actors){const p=a.model.position,dist=Math.hypot(player.x-p.x,player.z-p.z),targetHeight=crouch?1.08:1.72,visible=!lineBlocked(p.x,p.z,player.x,player.z,level.boxes,Math.min(1.6,targetHeight));a.model.rotation.y=Math.atan2(p.x-player.x,p.z-player.z);a.repath-=dt;let dx=0,dz=0;const speed=1.4+wave*.15;if(!visible||dist>16){if(a.repath<=0){a.path=routeTo(p,player,level.boxes);a.repath=1+Math.random()*.3;}const goal=a.path[0];if(goal){const d=Math.hypot(goal.x-p.x,goal.z-p.z);if(d<.35)a.path.shift();else{dx=(goal.x-p.x)/d*speed*dt;dz=(goal.z-p.z)/d*speed*dt;}}else if(visible&&dist>3){dx=(player.x-p.x)/dist*speed*dt;dz=(player.z-p.z)/dist*speed*dt;}}else if(dist<6){dx=(p.x-player.x)/dist*dt;dz=(p.z-player.z)/dist*dt;}else{dx=(player.z-p.z)/(dist||1)*.45*dt*a.strafe;dz=-(player.x-p.x)/(dist||1)*.45*dt*a.strafe;}const oldX=p.x,oldZ=p.z;moveActor(p,dx,dz,level.boxes,.43);if(actors.some(b=>b!==a&&Math.hypot(p.x-b.model.position.x,p.z-b.model.position.z)<.65)){p.x=oldX;p.z=oldZ;}const moving=Math.hypot(p.x-oldX,p.z-oldZ)>.001;a.model.userData.legs.forEach((leg,i)=>leg.rotation.x=moving?Math.sin(time*8+i*Math.PI)*.28:0);a.cool-=dt;if(a.cool<=0&&visible&&dist<29){a.cool=diff.interval+Math.random()*.6;const from=p.clone().add(new THREE.Vector3(0,1.2,-.2));const to=player.clone().add(new THREE.Vector3((Math.random()-.5)*.4,targetHeight-.1,0));tracer(from,to,0xe8a56d,.10);const playerMoving=Math.hypot(joystick.x,joystick.z)>.1||keys.has('KeyW')||keys.has('KeyA')||keys.has('KeyD')||keys.has('KeyS');const chance=diff.accuracy*(playerMoving?.65:1)*(dist>18?.65:1);if(Math.random()<chance){health-=diff.damage;damage=.7;sound('hurt');hud();if(health<=0){finish(false);return;}}}}}
function renderRadar(){const c=$('radar'),ctx=c.getContext('2d'),size=c.width,r=size/2;ctx.clearRect(0,0,size,size);ctx.save();ctx.beginPath();ctx.arc(r,r,r-1,0,Math.PI*2);ctx.clip();ctx.fillStyle='#172021b8';ctx.fillRect(0,0,size,size);ctx.translate(r,r);ctx.rotate(yaw);const s=4;ctx.fillStyle='#8a908377';for(const o of level.boxes)ctx.fillRect((o.x-player.x-o.w)*s,(o.z-player.z-o.d)*s,o.w*2*s,o.d*2*s);ctx.strokeStyle='#ffffff12';ctx.lineWidth=1;ctx.beginPath();ctx.arc(0,0,55,0,Math.PI*2);ctx.stroke();for(const a of actors){const x=(a.model.position.x-player.x)*s,z=(a.model.position.z-player.z)*s;if(Math.hypot(x,z)>r||lineBlocked(player.x,player.z,a.model.position.x,a.model.position.z,level.boxes,1.5))continue;ctx.fillStyle='#cc7763';ctx.beginPath();ctx.arc(x,z,3,0,7);ctx.fill();}ctx.restore();ctx.fillStyle='#e9dfc0';ctx.beginPath();ctx.moveTo(r,r-7);ctx.lineTo(r-5,r+5);ctx.lineTo(r+5,r+5);ctx.closePath();ctx.fill();}
let radarClock=0;function tick(dt){time+=dt;grade.uniforms.time.value=time;if(level)level.tick(dt,time);if(state==='playing'){elapsed+=dt;timeLeft=Math.max(0,timeLeft-dt);$('timer').textContent=formatTime(timeLeft);if(!timeLeft){finish(false);return;}shotCooldown=Math.max(0,shotCooldown-dt);if(reloadRemaining>0){const before=reloadRemaining;reloadRemaining=Math.max(0,reloadRemaining-dt);if(before>reloadTotal*.3&&reloadRemaining<=reloadTotal*.3)sound('reload');if(!reloadRemaining){Object.assign(ammoState[gunIndex],reloadAmmo(ammoState[gunIndex].ammo,ammoState[gunIndex].reserve,GUNS[gunIndex].capacity));sound('ready');hud();}}
 let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joystick.x,z=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+joystick.z;const len=Math.hypot(x,z);if(len>1){x/=len;z/=len;}const run=(sprinting||keys.has('ShiftLeft'))&&len>.1&&!aim&&!crouch&&!fireHeld;sprinting=touch?sprinting:false;const speed=crouch?2.2:aim?2.7:run?6.7:4.1;moveActor(player,(x*Math.cos(yaw)+z*Math.sin(yaw))*speed*dt,(-x*Math.sin(yaw)+z*Math.cos(yaw))*speed*dt,level.boxes,.38);if(len>.15){footstepTimer-=dt;if(footstepTimer<=0){sound('step');footstepTimer=run?.29:crouch?.59:.43;}}
 ads=THREE.MathUtils.damp(ads,aim&&!reloadRemaining&&!run?1:0,13,dt);recoil=THREE.MathUtils.damp(recoil,0,11,dt);const bob=reduced?0:Math.sin(time*(run?15:10))*Math.min(len,1)*.018*(1-ads);camera.position.set(player.x,(crouch?1.13:1.77)+bob,player.z);camera.rotation.set(pitch+recoil*.42,yaw,0);camera.fov=THREE.MathUtils.damp(camera.fov,ads>0?72-ads*25:run?78:72,11,dt);camera.updateProjectionMatrix();const gun=guns[gunIndex],sight=gun.userData.sightHeight;weaponRig.position.set(THREE.MathUtils.lerp(.24,0,ads)+lookSwayX*.008,THREE.MathUtils.lerp(-.26,-sight,ads)+bob*.25,-.48+recoil*.8);weaponRig.rotation.set(-recoil*1.5+(run?-.23:0),lookSwayX*.012,(run?-.22:0)+lookSwayY*.004);if(reloadRemaining){const p=1-reloadRemaining/reloadTotal,e=Math.sin(p*Math.PI);weaponRig.position.y-=e*.22;weaponRig.rotation.z-=e*.40;weaponRig.rotation.x-=e*.50;if(gun.userData.mag)gun.userData.mag.position.y=-.255-Math.sin(Math.min(1,p/.65)*Math.PI)*.22;if(gun.userData.leftHand)gun.userData.leftHand.position.y=-e*.13;}else{if(gun.userData.mag)gun.userData.mag.position.y=-.255;if(gun.userData.leftHand)gun.userData.leftHand.position.y=0;}
 lookSwayX=THREE.MathUtils.damp(lookSwayX,0,9,dt);lookSwayY=THREE.MathUtils.damp(lookSwayY,0,9,dt);$('crosshair').style.opacity=String((1-ads)*.7);$('crosshair').style.transform=`translate(-50%,-50%) scale(${1+recoil*12+(len>.1?.1:0)})`;if(fireHeld)shoot();tickActors(dt);radarClock-=dt;if(radarClock<=0){renderRadar();radarClock=.1;}$('compass').textContent=['N','NW','W','SW','S','SE','E','NE'][((Math.round(yaw/(Math.PI/4))%8)+8)%8];if(transition>0&&state==='playing'){transition-=dt;if(transition<=0){if(wave===3)finish(true);else spawnWave();}}
 }else if(state==='lobby'||state==='loading'){camera.position.set(-2.4,2.35,14.5);camera.lookAt(-.45,1.35,21);camera.fov=49;camera.updateProjectionMatrix();hero.position.set(1.65,0,20.5);hero.scale.setScalar(1.27);hero.rotation.y=-.12+(reduced?0:Math.sin(time*.18)*.06);}
 damage=Math.max(0,damage-dt);$('damage').style.opacity=damage;hitTimer=Math.max(0,hitTimer-dt);$('hitmarker').style.opacity=hitTimer>0?1:0;flashTimer=Math.max(0,flashTimer-dt);guns.forEach((g,i)=>{g.userData.flash.visible=state==='playing'&&i===gunIndex&&flashTimer>0;});muzzleLight.intensity=flashTimer>0?3:0;noticeTimer=Math.max(0,noticeTimer-dt);if(!noticeTimer)$('notice').textContent='';feedTimer=Math.max(0,feedTimer-dt);if(!feedTimer)$('killfeed').textContent='';for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.life-=dt;e.obj.material.opacity=Math.max(0,e.life/e.total);if(e.vel){const p=e.obj.geometry.attributes.position;for(let j=0;j<e.vel.length;j++){e.vel[j].y-=dt*4;p.array[j*3]+=e.vel[j].x*dt;p.array[j*3+1]+=e.vel[j].y*dt;p.array[j*3+2]+=e.vel[j].z*dt;}p.needsUpdate=true;}if(e.life<=0){scene.remove(e.obj);e.obj.geometry.dispose();e.obj.material.dispose();effects.splice(i,1);}}if(level){if(low)renderer.render(scene,camera);else composer.render();}}
// Controls use pointer capture so releasing outside a button cannot leave fire or movement stuck.
let lookId=null,lookX=0,lookY=0,stickId=null;function turn(dx,dy){const sense=Number($('sensitivity').value);yaw-=dx*(touch?.0042:.0020)*sense*(aim?.62:1);pitch=THREE.MathUtils.clamp(pitch-dy*(touch?.0033:.0018)*sense*(aim?.62:1),-1.15,1.15);lookSwayX=THREE.MathUtils.clamp(dx,-3,3);lookSwayY=THREE.MathUtils.clamp(dy,-3,3);}
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;if(touch||document.pointerLockElement!==canvas){lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;canvas.setPointerCapture(e.pointerId);if(!touch)pointerLock();}if(!touch){if(e.button===0){fireHeld=true;semiReady=true;}if(e.button===2)aim=true;}});canvas.addEventListener('pointermove',e=>{if(state!=='playing')return;if(!touch&&document.pointerLockElement===canvas){turn(e.movementX,e.movementY);return;}if(e.pointerId===lookId){turn(e.clientX-lookX,e.clientY-lookY);lookX=e.clientX;lookY=e.clientY;}});function releaseLook(e){if(e.pointerId===lookId)lookId=null;if(!touch){if(e.button===0)fireHeld=false;if(e.button===2)aim=false;}}addEventListener('pointerup',releaseLook);canvas.addEventListener('pointercancel',()=>{lookId=null;fireHeld=false;aim=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!touch)pause();});
addEventListener('keydown',e=>{if(state!=='playing')return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR')reload();if(e.code==='KeyC'){crouch=!crouch;hud();}if(e.code==='Digit1')switchGun(0);if(e.code==='Digit2')switchGun(1);if(e.code==='Escape'||e.code==='KeyP')pause();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
const stick=$('stick');function moveStick(e){if(e.pointerId!==stickId||state!=='playing')return;const r=stick.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/38,z=(e.clientY-r.top-r.height/2)/38;const d=Math.hypot(x,z);if(d>1){x/=d;z/=d;}joystick.x=x;joystick.z=z;stick.firstElementChild.style.transform=`translate(${x*28}px,${z*28}px)`;}stick.onpointerdown=e=>{if(state!=='playing')return;stickId=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e);};stick.onpointermove=moveStick;for(const event of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(event,e=>{if(e.pointerId===stickId){stickId=null;joystick.x=joystick.z=0;stick.firstElementChild.style.transform='';}});
$('touchFire').onpointerdown=e=>{if(state!=='playing')return;e.preventDefault();$('touchFire').setPointerCapture(e.pointerId);fireHeld=true;semiReady=true;};for(const event of ['pointerup','pointercancel','lostpointercapture'])$('touchFire').addEventListener(event,()=>fireHeld=false);$('touchReload').onclick=reload;$('touchSwitch').onclick=()=>switchGun(1-gunIndex);$('touchAim').onclick=()=>{aim=!aim;$('touchAim').setAttribute('aria-pressed',String(aim));};$('touchCrouch').onclick=()=>{crouch=!crouch;$('touchCrouch').setAttribute('aria-pressed',String(crouch));hud();};$('touchSprint').onclick=()=>{sprinting=!sprinting;$('touchSprint').setAttribute('aria-pressed',String(sprinting));hud();};
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen?.();if(touch)await screen.orientation?.lock?.('landscape');}catch{/* iOS may require manual rotation; the HUD provides the hint. */}}
$('fullscreen').onclick=fullscreen;$('start').onclick=start;$('pauseButton').onclick=pause;$('continue').onclick=()=>state==='paused'?resume():start();$('return').onclick=returnLobby;$('sound').onclick=()=>{muted=!muted;$('sound').textContent='音效：'+(muted?'關閉':'開啟');$('sound').setAttribute('aria-pressed',String(!muted));if(master)master.gain.value=muted?0:.65;};for(const [tab,panel]of [['deployTab','deployPanel'],['settingsTab','settingsPanel']])$(tab).onclick=()=>{for(const [t,p]of [['deployTab','deployPanel'],['settingsTab','settingsPanel']]){$(t).classList.toggle('active',t===tab);$(p).hidden=p!==panel;}};document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{if(state==='lobby'&&b.dataset.map!==map)setMap(b.dataset.map);});$('quality').onchange=()=>{if(state==='lobby')setMap(map);};addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();applyQuality();});
let last=performance.now();function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;try{tick(dt);}catch(e){console.error(e);pause();$('fatal').hidden=false;$('fatalMessage').textContent='遊戲執行發生錯誤，請重新載入。';return;}requestAnimationFrame(frame);}
try{await loadMaterials();setMap('foundry');state='lobby';$('start').disabled=false;$('start').firstElementChild.textContent='開始行動';$('loading').textContent=touch?'手機橫向 · 觸控操作':'WASD 移動 · 滑鼠瞄準 · Esc 暫停';requestAnimationFrame(frame);}catch(e){console.error(e);$('fatal').hidden=false;$('fatalMessage').textContent='無法載入場景材質，請確認網路連線後重新載入。';}
