import * as THREE from 'three';
import { weapons, waveSize, rayCircle, moveCircle } from './rules.js';
const $=id=>document.getElementById(id), canvas=$('game'), mobile=matchMedia('(pointer:coarse)').matches;
let renderer;
try { renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}); }
catch { $('load').textContent='無法啟動 3D，請使用支援 WebGL 的瀏覽器並開啟硬體加速。'; $('start').disabled=true; throw new Error('WebGL unavailable'); }
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1.4:1.8));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new THREE.Scene();scene.background=new THREE.Color('#081622');scene.fog=new THREE.FogExp2('#0c2130',.019);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.08,160);camera.rotation.order='YXZ';
scene.add(new THREE.HemisphereLight(0x8eceff,0x314029,2.1));const moon=new THREE.DirectionalLight(0xc1defa,2.7);moon.position.set(-12,30,14);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);Object.assign(moon.shadow.camera,{left:-48,right:48,top:48,bottom:-48});scene.add(moon);scene.add(moon.target);
const world=new THREE.Group();scene.add(world);let obstacles=[],bots=[],effects=[],packs=[],state='menu',time=0,wave=0,score=0,kills=0,health=100,ammo=12,weaponIndex=0,reloading=0,cooldown=0,spawnDelay=0,hurt=0,hitTime=0,noticeTime=0,third=true,aim=false,fire=false,muted=false,audioCtx;
let yaw=0,pitch=0,player=new THREE.Vector3(0,0,15),elapsed=0,shotCount=0,hitCount=0;
const keys=new Set(),move={x:0,y:0};const mat=(color,metalness=0,roughness=.75)=>new THREE.MeshStandardMaterial({color,metalness,roughness});
const cream=mat('#fff0c8'),yellow=mat('#f6b929'),red=mat('#af2333'),pink=mat('#e5a790'),black=mat('#141920'),eyeMat=mat('#080c11',.3,.16),blue=mat('#142e41',.5,.35),metal=mat('#40566b',.7,.3);
function mesh(geo,m,x=0,y=0,z=0,parent=world){const o=new THREE.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,m,x,y,z,parent=world){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,parent);}
function ball(x,y,z,sx,sy,sz,m,parent){const o=mesh(new THREE.SphereGeometry(1,20,14),m,x,y,z,parent);o.scale.set(sx,sy,sz);return o;}
function glow(color){return new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:3});}
const cyan=glow('#25bfe9'),amber=glow('#ffb144'),redGlow=glow('#f85161');
function duck(){const g=new THREE.Group();ball(0,.9,0,.48,.53,.33,pink,g);ball(0,1.38,0,.49,.4,.34,red,g);ball(0,1.96,0,.54,.55,.46,cream,g);ball(0,2.31,.04,.55,.27,.46,black,g);const brim=ball(0,2.24,-.25,.57,.10,.40,black,g);ball(0,1.84,-.46,.31,.16,.24,yellow,g);for(const s of [-1,1]){ball(s*.235,2.05,-.409,.074,.10,.052,eyeMat,g);ball(s*.22,2.085,-.455,.021,.028,.014,cream,g);ball(s*.38,1.86,-.345,.068,.035,.02,pink,g);}const legs=[],arms=[];for(const s of [-1,1]){const leg=new THREE.Group();leg.position.set(s*.25,.48,0);g.add(leg);ball(0,-.17,-.12,.22,.17,.31,yellow,leg);legs.push(leg);const arm=new THREE.Group();arm.position.set(s*.45,1.5,0);g.add(arm);ball(s*.07,-.19,0,.15,.31,.16,cream,arm);ball(s*.03,-.04,0,.17,.18,.18,red,arm);arms.push(arm);}const knot=ball(0,1.62,-.33,.06,.055,.04,red,g);for(const s of [-1,1]){const ribbon=ball(s*.105,1.58,-.35,.12,.05,.045,red,g);ribbon.rotation.z=s*.5;}ball(-.24,1.51,-.3,.055,.055,.04,yellow,g);const gun=box(.13,.16,.44,metal,.55,1.16,-.29,g);box(.075,.055,.25,cyan,.55,1.2,-.4,g);g.userData={legs,arms,gun};return g;}
const hero=duck();scene.add(hero);
const viewGun=new THREE.Group();box(.14,.18,.48,metal,0,0,0,viewGun);box(.10,.07,.32,cyan,0,.08,-.07,viewGun);box(.10,.24,.13,black,0,-.15,.14,viewGun);ball(0,-.15,.14,.12,.17,.15,cream,viewGun);camera.add(viewGun);scene.add(camera);viewGun.visible=false;
function sign(text,color,w=3){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#091722';ctx.fillRect(0,0,512,128);ctx.strokeStyle=color;ctx.lineWidth=5;ctx.strokeRect(4,4,504,120);ctx.fillStyle=color;ctx.font='bold 54px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,68);const t=new THREE.CanvasTexture(c);const m=new THREE.MeshBasicMaterial({map:t});return new THREE.Mesh(new THREE.PlaneGeometry(w,w/4),m);}
function clearGroup(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material?.map){o.material.map.dispose();o.material.dispose();}});g.clear();}
function buildMap(kind){clearGroup(world);obstacles=[];packs=[];bots=[];effects=[];const ground=mat('#142832',.35,.6);box(90,.15,90,ground,0,-.1,0);const road=mat('#0c1822',.25,.6);box(15,.03,80,road,0,.01,0);for(let z=-38;z<40;z+=5)box(.13,.02,2,amber,0,.04,z);
 const buildingMats=[mat('#263d4d',.25),mat('#192c40',.35),mat('#33434d',.2)];
 for(let s of [-1,1])for(let i=0;i<7;i++){let z=-32+i*10,x=s*(15+(i%2)*2),h=7+(i*7%11),w=8;box(w,h,8,buildingMats[i%3],x,h/2,z);obstacles.push({x,z,w:w/2,d:4});box(w+.4,.3,8.4,metal,x,h,z);for(let fy=2;fy<h-1;fy+=2.3)for(let fx=-2.5;fx<=2.5;fx+=2.5){box(.8,1.1,.04,(i+Math.round(fy))%3?cyan:amber,x+fx,fy,z+4.03);}box(w,.12,.1,i%2?cyan:redGlow,x,1,z+4.06);if(i%2===0){const a=sign(i===2?'DUCK POLICE':i===4?'NIGHT MARKET':'HARBOR 07',i%4?'#ffad7e':'#76e9ff',6);a.position.set(x,4,z+4.07);world.add(a);}}
 const placements=kind==='harbor'?[[-5,-19,3,2],[5,-7,3,2],[-4,3,2,2],[5,18,2,3],[-6,27,3,2],[6,-30,2,3]]:[[-5,-24,2,2],[5,-24,2,2],[-5,1,2,2],[5,1,2,2],[-5,25,2,2],[5,25,2,2]];
 for(const [x,z,w,d]of placements){box(w,1.4,d,mat('#304957',.45),x,.7,z);box(w,.1,d+.04,amber,x,1.4,z);obstacles.push({x,z,w:w/2,d:d/2});}
 if(kind==='square'){box(3,.55,5,metal,0,.28,-10);obstacles.push({x:0,z:-10,w:1.5,d:2.5});const statue=duck();statue.position.set(0,.6,-10);statue.scale.setScalar(1.5);world.add(statue);}else{for(let i=0;i<3;i++){box(4,2.4,6,mat(i%2?'#72434a':'#28616b',.4),-28,1.2,-12+i*8);}}
 for(let s of [-1,1])for(let z=-30;z<39;z+=12){box(.12,4.7,.12,metal,s*8,2.35,z);box(1.1,.15,.4,cyan,s*8,4.7,z);const light=new THREE.PointLight(0x37cfff,12,11,2);light.position.set(s*8,4,z);world.add(light);}
 for(const [x,z]of [[-6,12],[6,-15],[-6,-32]]){const p=new THREE.Group();box(.65,.65,.65,mat('#f1e9d6'),0,0,0,p);box(.4,.09,.02,redGlow,0,0,.34,p);box(.09,.4,.02,redGlow,0,0,.35,p);p.position.set(x,.6,z);world.add(p);packs.push(p);}
 // Police vehicle beside the avenue.
 const car=new THREE.Group();box(2.1,.7,4,blue,0,.6,0,car);box(1.8,.65,1.8,mat('#91b6c5',.65,.18),0,1.2,-.1,car);box(.65,.16,.3,redGlow,-.4,1.6,0,car);box(.65,.16,.3,cyan,.4,1.6,0,car);for(const s of [-1,1])for(const z of [-1.25,1.25]){const t=mesh(new THREE.CylinderGeometry(.4,.4,.2,14),black,s*1.05,.4,z,car);t.rotation.z=Math.PI/2;}car.position.set(6,0,9);world.add(car);obstacles.push({x:6,z:9,w:1.2,d:2.1});
}
function robot(x,z){const g=new THREE.Group();box(.65,.75,.42,blue,0,1,0,g);ball(0,1.63,0,.34,.32,.29,metal,g);box(.44,.075,.05,redGlow,0,1.65,.27,g);for(const s of [-1,1]){box(.18,.58,.19,metal,s*.21,.36,0,g);box(.18,.6,.18,metal,s*.43,.95,0,g);}g.position.set(x,0,z);world.add(g);return {g,hp:weapons.difficulty[$('difficulty').value].hp,cool:1+Math.random(),phase:Math.random()*6};}
function spawnWave(){wave++;spawnDelay=0;const n=waveSize(wave,$('difficulty').value);for(let i=0;i<n;i++){let x,z,tries=0;do{x=(Math.random()-.5)*13;z=-32+Math.random()*60;tries++;}while(tries<100&&(Math.hypot(x-player.x,z-player.z)<12||obstacles.some(o=>Math.abs(o.x-x)<o.w+1&&Math.abs(o.z-z)<o.d+1)));bots.push(robot(x,z));}notify(`第 ${wave} 波來襲`);updateHUD();}
function updateHUD(){$('health').textContent=Math.max(0,Math.ceil(health));$('healthbar').style.width=`${Math.max(0,health)}%`;$('ammo').textContent=ammo;$('capacity').textContent=` / ${weapons.list[weaponIndex].capacity}`;$('weapon').textContent=weapons.list[weaponIndex].name;$('score').textContent=String(score).padStart(4,'0');$('wave').textContent=`第 ${wave} / 3 波`;$('remaining').textContent=`剩餘目標 ${bots.length}　｜　已攔截 ${kills}`;$('reloadText').textContent=reloading?'換彈中…':'R 換彈 · 1 / 2 切換装備';}
function notify(t){$('notice').textContent=t;noticeTime=2.5;}
function beep(freq=500,duration=.08,type='sine',volume=.08){if(muted||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.35,audioCtx.currentTime+duration);g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}
function streak(a,b,color){const geom=new THREE.BufferGeometry().setFromPoints([a,b]),line=new THREE.Line(geom,new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));world.add(line);effects.push({o:line,t:.1,max:.1});}
const ray=new THREE.Raycaster(),direction=new THREE.Vector3();
function shoot(){if(state!=='playing'||cooldown>0||reloading>0)return;if(ammo<=0){reload();return;}ammo--;shotCount++;const w=weapons.list[weaponIndex];cooldown=w.delay;beep(weaponIndex?150:270,.09,'sawtooth',.035);camera.getWorldDirection(direction);ray.set(camera.position,direction);ray.far=80;
 // Raycast blockers and targets together: bullets cannot travel through cover.
 const candidates=[];for(const b of bots)b.g.traverse(o=>{if(o.isMesh){o.userData.bot=b;candidates.push(o);}});world.traverse(o=>{if(o.isMesh&&!o.userData.bot&&!packs.some(p=>o.parent===p)&&!effects.some(e=>e.o===o))candidates.push(o);});
 const hits=ray.intersectObjects(candidates,false);const end=hits.length?hits[0].point:camera.position.clone().addScaledVector(direction,70);const from=third?hero.localToWorld(new THREE.Vector3(.55,1.2,-.65)):viewGun.localToWorld(new THREE.Vector3(0,0,-.3));streak(from,end,0xc4ff9c);
 const b=hits[0]?.object.userData.bot;if(b){b.hp-=w.damage;hitCount++;hitTime=.13;beep(750,.05,'sine',.045);if(b.hp<=0){world.remove(b.g);b.g.traverse(o=>o.geometry?.dispose());bots.splice(bots.indexOf(b),1);score+=100*wave;kills++;notify('目標已攔截 +'+100*wave);if(!bots.length)spawnDelay=2.5;}}updateHUD();}
function reload(){if(state!=='playing'||reloading||ammo===weapons.list[weaponIndex].capacity)return;reloading=weapons.list[weaponIndex].reload;beep(450,.12,'triangle');updateHUD();}
function switchWeapon(i){if(state!=='playing'||i===weaponIndex)return;weaponIndex=i;ammo=0;reloading=weapons.list[i].reload;cooldown=.2;updateHUD();}
function requestLock(){if(!mobile&&canvas.requestPointerLock){try{const p=canvas.requestPointerLock();p?.catch(()=>notify('點擊遊戲畫面以啟用滑鼠轉向'));}catch{notify('點擊遊戲畫面以啟用滑鼠轉向');}}}
function start(){buildMap($('map').value);player.set(0,0,20);yaw=0;pitch=0;health=100;score=0;kills=0;wave=0;weaponIndex=0;ammo=12;reloading=0;cooldown=0;hurt=0;elapsed=0;shotCount=0;hitCount=0;spawnDelay=0;state='playing';third=true;fire=false;aim=false;keys.clear();for(const id of ['menu','agent','pause','result'])$(id).hidden=true;$('hud').hidden=false;$('touch').hidden=!mobile;document.body.classList.add('playing');if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();}catch{}}audioCtx?.resume();spawnWave();requestLock();}
function pause(){if(state!=='playing')return;state='paused';fire=false;keys.clear();move.x=move.y=0;$('joystick').firstElementChild.style.transform='';$('pause').hidden=false;document.exitPointerLock?.();}
function resume(){state='playing';$('pause').hidden=true;requestLock();}
function menu(){state='menu';fire=false;keys.clear();document.exitPointerLock?.();['hud','pause','result','touch'].forEach(id=>$(id).hidden=true);$('menu').hidden=false;$('agent').hidden=false;document.body.classList.remove('playing');buildMap($('map').value);}
function finish(win){state='result';fire=false;document.exitPointerLock?.();$('touch').hidden=true;$('result').hidden=false;$('resultTitle').textContent=win?'任務完成，城市安全。':'特工，整裝再出發。';$('resultStats').textContent=`行動分數 ${score} · 攔截 ${kills} 個目標 · ${Math.floor(elapsed)} 秒 · 命中率 ${shotCount?Math.round(hitCount/shotCount*100):0}%`;beep(win?900:120,.4,'triangle');}
function tick(dt){time+=dt;if(state==='playing'){elapsed+=dt;cooldown=Math.max(0,cooldown-dt);if(reloading>0){reloading-=dt;if(reloading<=0){reloading=0;ammo=weapons.list[weaponIndex].capacity;beep(620,.07);updateHUD();}}if(fire)shoot();
 let mx=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+move.x,mz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+move.y;const len=Math.hypot(mx,mz);if(len>1){mx/=len;mz/=len;}const speed=aim?2.7:keys.has('ShiftLeft')?8:5;const dx=(mx*Math.cos(yaw)+mz*Math.sin(yaw))*speed*dt,dz=(-mx*Math.sin(yaw)+mz*Math.cos(yaw))*speed*dt;moveCircle(player,dx,dz,obstacles,.4);player.x=THREE.MathUtils.clamp(player.x,-9,9);player.z=THREE.MathUtils.clamp(player.z,-37,37);hero.position.copy(player);hero.rotation.y=yaw;hero.userData.legs.forEach((l,i)=>l.rotation.x=len?Math.sin(time*12+i*Math.PI)*.5:0);hero.userData.arms.forEach((a,i)=>a.rotation.x=len?Math.sin(time*12+i*Math.PI)*.2:0);
 camera.rotation.set(pitch,yaw,0);const offset=new THREE.Vector3(third?.75:0,third?2.8:2.0,third?(aim?2.1:4.5):0).applyAxisAngle(new THREE.Vector3(0,1,0),yaw);camera.position.copy(player).add(offset);camera.fov=THREE.MathUtils.lerp(camera.fov,aim?43:third?65:72,.15);camera.updateProjectionMatrix();hero.visible=third;viewGun.visible=!third;viewGun.position.set(aim?.12:.3,-.28-Math.sin(time*10)*Math.min(len,.8)*.014,-.6+Math.max(0,cooldown)*.25);viewGun.rotation.x=reloading?-.55:0;
 const difficulty=weapons.difficulty[$('difficulty').value];for(const b of bots){const dx=player.x-b.g.position.x,dz=player.z-b.g.position.z,dist=Math.hypot(dx,dz);b.g.rotation.y=Math.atan2(dx,dz);b.g.position.y=Math.sin(time*5+b.phase)*.035;const clear=!obstacles.some(o=>rayCircle(b.g.position.x,b.g.position.z,player.x,player.z,o,.12));if(dist>7||!clear){const speed=1.3+wave*.3;let vx=dx/(dist||1)*speed*dt,vz=dz/(dist||1)*speed*dt;const prev=b.g.position.clone();moveCircle(b.g.position,vx,vz,obstacles,.5);if(b.g.position.distanceTo(prev)<dt*.3){moveCircle(b.g.position,Math.cos(b.phase)*speed*dt,Math.sin(b.phase)*speed*dt,obstacles,.5);b.phase+=dt*.5;}}b.cool-=dt;if(dist<24&&b.cool<=0&&clear){b.cool=difficulty.interval+Math.random()*.6;streak(b.g.position.clone().add(new THREE.Vector3(0,1.2,0)),player.clone().add(new THREE.Vector3(0,1.2,0)),0xff676b);if(Math.random()<(len>.2?.35:.75)){health-=difficulty.damage;hurt=.7;beep(90,.10,'triangle',.04);updateHUD();if(health<=0){finish(false);break;}}}}
 for(const p of packs){if(!p.visible)continue;p.rotation.y+=dt;p.position.y=.65+Math.sin(time*2)*.08;if(p.position.distanceTo(player)<1.2&&health<100){health=Math.min(100,health+35);p.visible=false;notify('急救補給 +35');beep(1000,.15);updateHUD();}}
 if(spawnDelay>0){spawnDelay-=dt;if(spawnDelay<=0){if(wave>=3)finish(true);else spawnWave();}}
 }else if(state==='menu'){hero.visible=true;viewGun.visible=false;hero.position.set(0,0,15);hero.rotation.y=-.35+Math.sin(time*.3)*.10;hero.userData.legs.forEach(l=>l.rotation.x=0);camera.position.set(-3.4,2.75,8.6);camera.lookAt(-1.6,1.35,15);camera.fov=50;camera.updateProjectionMatrix();}
 for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.t-=dt;e.o.material.opacity=Math.max(0,e.t/e.max);if(e.t<=0){world.remove(e.o);e.o.geometry.dispose();e.o.material.dispose();effects.splice(i,1);}}
 hurt=Math.max(0,hurt-dt);hitTime=Math.max(0,hitTime-dt);noticeTime=Math.max(0,noticeTime-dt);$('damage').style.opacity=hurt;$('hit').style.opacity=hitTime>0?1:0;if(!noticeTime)$('notice').textContent='';renderer.render(scene,camera);
}
let last=performance.now();function loop(now){const dt=Math.min((now-last)/1000,.045);last=now;tick(dt);requestAnimationFrame(loop);}buildMap('harbor');$('load').textContent='行動現場已就緒';requestAnimationFrame(loop);
$('start').onclick=start;$('again').onclick=start;$('resume').onclick=resume;$('quit').onclick=menu;$('back').onclick=menu;$('pauseButton').onclick=pause;$('map').onchange=()=>buildMap($('map').value);$('sound').onclick=()=>{muted=!muted;$('sound').textContent='音效：'+(muted?'關':'開');};
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
addEventListener('keydown',e=>{if(state!=='playing')return;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyR')reload();if(e.code==='KeyV')third=!third;if(e.code==='Digit1')switchWeapon(0);if(e.code==='Digit2')switchWeapon(1);if(e.code==='Escape')pause();});addEventListener('keyup',e=>keys.delete(e.code));
addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing'&&!mobile)pause();});
canvas.addEventListener('pointerdown',e=>{if(state!=='playing'||mobile)return;if(document.pointerLockElement!==canvas){requestLock();return;}if(e.button===0)fire=true;if(e.button===2)aim=true;});addEventListener('pointerup',e=>{if(!mobile&&e.button===0)fire=false;if(e.button===2)aim=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(state==='playing'&&document.pointerLockElement===canvas){yaw-=e.movementX*.0025;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.002,-1.0,1.0);}});
let lookId=null,lookX=0,lookY=0;canvas.addEventListener('pointerdown',e=>{if(!mobile||state!=='playing')return;lookId=e.pointerId;lookX=e.clientX;lookY=e.clientY;canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||state!=='playing')return;yaw-=(e.clientX-lookX)*.006;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lookY)*.004,-1,1);lookX=e.clientX;lookY=e.clientY;});for(const name of ['pointerup','pointercancel'])canvas.addEventListener(name,()=>lookId=null);
let joyId=null;const joy=$('joystick');function joyMove(e){if(e.pointerId!==joyId)return;const r=joy.getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/40,y=(e.clientY-r.top-r.height/2)/40;const l=Math.hypot(x,y);if(l>1){x/=l;y/=l;}move.x=x;move.y=y;joy.firstElementChild.style.transform=`translate(${x*32}px,${y*32}px)`;}joy.onpointerdown=e=>{joyId=e.pointerId;joy.setPointerCapture(e.pointerId);joyMove(e);};joy.onpointermove=joyMove;for(const name of ['pointerup','pointercancel'])joy.addEventListener(name,()=>{joyId=null;move.x=move.y=0;joy.firstElementChild.style.transform='';});
$('fireTouch').onpointerdown=e=>{e.preventDefault();$('fireTouch').setPointerCapture(e.pointerId);fire=true;};for(const name of ['pointerup','pointercancel'])$('fireTouch').addEventListener(name,()=>fire=false);$('reloadTouch').onclick=reload;$('viewTouch').onclick=()=>third=!third;$('weaponTouch').onclick=()=>switchWeapon(1-weaponIndex);$('aimTouch').onclick=()=>{aim=!aim;$('aimTouch').textContent=aim?'取消瞄準':'瞄準';};
